### ISSUE TITLE
the Promize and `.renderAsync`

### ISSUE THREAD

**Issue by tunnckoCore** [jstransformers/jstransformer-rho#1]
`.renderAsync` is implemented because [their notice](https://github.com/inca/rho#synchronous-rendering) in the readme
and second, because my state here https://github.com/jstransformers/jstransformer-jst/issues/1#issuecomment-130901830, we always should implement transformer's methods, cuz they can give some wanted things.

`Promize` instead of `Promise` cuz it breaks some things and because it would override global Promise in newer node versions, with what im not agree.

**Comment by RobLoach** [comment]
> Promize instead of Promise cuz it breaks some things and because it would override global Promise in newer node versions, with what im not agree.

The [Promise module](http://npm.im/promise) is standard-compliant with ES6 Promises. "Overriding globally" is incorrect since `var Promise =` is a locally scoped variable. CommonJS and its module spec keeps everything to scoped to what's in the module... I suggest you use `var Promise = require('promise')` until we deprecated node 0.10.

**Comment by RobLoach** [comment]
> .renderAsync is implemented....

:+1: Looks like it's mostly asynchronous, so this is correct.
